ALTER USER docker WITH PASSWORD 'docker5820?';
CREATE DATABASE docker;
GRANT ALL PRIVILEGES ON DATABASE docker TO docker;

CREATE USER root WITH PASSWORD 'EbaniyAdmin1337!';
CREATE DATABASE root;
GRANT ALL PRIVILEGES ON DATABASE root TO root;
-- GRANT ALL PRIVILEGES ON DATABASE 